hualiang.he/modulo 2
hhualiang/themoviedb pull request #1
Opened 2023-08-16 14:57 UTC by hhualiang

First PR for the second module.
Screen with an app bar on the top with navigation back button and a search button.
Two photos, a movie poster and a promotional poster. The movie name displayed with it's release date.
The qualification of the movie, genres of the movie and an overview.
Counter of likes given by the user, persistent using shared preferences.

![demo](https://github.com/hhualiang/themoviedb/assets/117481923/70bfbc8b-f5bb-4f91-90d1-6296ed31026b)

2023-08-16 15:03 UTC, LeonardoMolleker commented on lib/genres_text.dart
> +      padding: const EdgeInsets.symmetric(horizontal: 5),
Constant

2023-08-16 15:03 UTC, LeonardoMolleker commented on lib/genres_text.dart
> +          borderRadius: BorderRadius.circular(8),
Constant

2023-08-16 15:03 UTC, LeonardoMolleker commented on lib/genres_text.dart
> +            width: 3,
Constant

2023-08-16 15:03 UTC, LeonardoMolleker commented on lib/genres_text.dart
> +              fontSize: 16,
Constant

2023-08-16 15:04 UTC, LeonardoMolleker commented on lib/genres_text.dart
> +            )),
Trailing comma

2023-08-16 15:06 UTC, LeonardoMolleker commented on lib/main.dart
> +    final prefs = await SharedPreferences.getInstance();
Let's call the shared preferences instance only once

2023-08-16 15:06 UTC, LeonardoMolleker commented on lib/main.dart
> +      _counter = (prefs.getInt('counter') ?? 0);
A constant for the 'counter' key would be fine

2023-08-16 15:08 UTC, hhualiang commented on lib/genres_text.dart
> +      padding: const EdgeInsets.symmetric(horizontal: 5),
I cant make padding constant because it has a container inside

2023-08-16 15:09 UTC, LeonardoMolleker commented on lib/main.dart
> +          title: const Text('The Super Mario Bros. Movie'),
Constant

2023-08-16 15:09 UTC, LeonardoMolleker commented on lib/main.dart
> +                })
Trailing commna

2023-08-16 15:09 UTC, LeonardoMolleker commented on lib/main.dart
> +                        'https://image.tmdb.org/t/p/w500/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg'),
Constant

2023-08-16 15:10 UTC, hhualiang commented on lib/genres_text.dart
> +              fontSize: 16,
It doesn't allow me to make Text constant due to text being a variable.

2023-08-16 15:14 UTC, LeonardoMolleker commented on lib/showAlertDialog.dart
> +showAlertDialog(BuildContext context) {
Instead of let the code loose, we can put these methods inside an abstract class and call them as a static methods, what do you think?

2023-08-16 15:14 UTC, LeonardoMolleker commented on lib/title_text.dart
> +        fontSize: 20,
constant

2023-08-16 15:14 UTC, LeonardoMolleker commented on lib/main.dart
> +                  ))
comma

2023-08-16 15:14 UTC, LeonardoMolleker commented on lib/main.dart
> +                          ))
comma

2023-08-16 15:14 UTC, LeonardoMolleker commented on lib/main.dart
> +                        width: 30,
Constant

2023-08-16 15:14 UTC, LeonardoMolleker commented on lib/main.dart
> +                                color: Colors.white, fontSize: 20),
Constant

2023-08-16 15:15 UTC, LeonardoMolleker commented on lib/main.dart
> +                        width: 40,
Constants

2023-08-16 15:15 UTC, LeonardoMolleker commented on lib/main.dart
> +                right: 0,
Constants

2023-08-16 15:15 UTC, LeonardoMolleker commented on lib/main.dart
> +                              GenresText(text: 'Comedy'),
Constants

2023-08-16 15:15 UTC, LeonardoMolleker commented on lib/main.dart
> +                  )),
Constants, and trailing comma

2023-08-16 15:15 UTC, LeonardoMolleker commented on lib/main.dart
> +                          color: Colors.white,
Constants

2023-08-16 15:15 UTC, LeonardoMolleker commented on lib/main.dart
> +                          fontSize: 20,
Constants

2023-08-16 15:15 UTC, LeonardoMolleker commented on lib/main.dart
> +                      'https://image.tmdb.org/t/p/w500/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
Constants

2023-08-16 15:16 UTC, FranciscoGaraventa requested changes
Remove demo folder, you are adding space to the app that is no need it, use the images for the demo to show in on the PR only

2023-08-16 15:16 UTC, LeonardoMolleker commented on lib/main.dart
> +                })
duplicated code here!

2023-08-16 15:17 UTC, FranciscoGaraventa commented on lib/genres_text.dart
> +              fontSize: 16,
You need to move const from TextStyle to Text like this
`child: const Text(...)`

2023-08-16 15:19 UTC, FranciscoGaraventa commented on lib/main.dart
> +                  )),
trailing comma

2023-08-16 15:19 UTC, FranciscoGaraventa commented on lib/main.dart
> +                              EdgeInsets.symmetric(horizontal: 5, vertical: 4),
trailing comma

2023-08-16 15:20 UTC, FranciscoGaraventa commented on lib/main.dart
> +                          )),
trailing comma

2023-08-16 15:20 UTC, FranciscoGaraventa commented on lib/main.dart
> +                                color: Colors.white, fontSize: 20),
And also you missed to add a trailing comma

2023-08-16 15:22 UTC, MarcosCGlobant commented on lib/showAlertDialog.dart
> +showAlertDialog(BuildContext context) {
and with that change, refactor the file name to keep the convention, lower case with words separated with underscores, using the name of the abstract class

2023-08-17 13:53 UTC, matiasilveiro-gl reviewed
I think this is a good time to split your huge widget tree into smaller and specific parts, like "MovieHeader" (with the title, release date and votes avg), "GenresView" (with the title and the genres list", and so on.
Thoughts?

2023-08-17 13:53 UTC, matiasilveiro-gl commented on lib/Utils/ui_text.dart
> +}
EOF

2023-08-18 15:36 UTC, LeonardoMolleker commented on lib/main.dart
> +class ContainerCounter extends StatelessWidget {
Let's move this widget to a new file

2023-08-18 15:36 UTC, LeonardoMolleker commented on lib/main.dart
> +class LikeButtonEndSpacer extends StatelessWidget {
Same as above

2023-08-18 15:36 UTC, LeonardoMolleker commented on lib/main.dart
> +class HorizontalSpacer extends StatelessWidget {
Same as above

2023-08-18 15:36 UTC, LeonardoMolleker commented on lib/main.dart
> +  const HorizontalSpacer({
Same as above

2023-08-18 16:54 UTC, FranciscoGaraventa commented on lib/main.dart
> +  }
This functionality that you have here could be wrapped in only one method.
You can have a `void changeCounterState()`

2023-08-18 16:56 UTC, FranciscoGaraventa commented on lib/main.dart
> +  }
And also check the variables names, dont use number on constants and also use lowerCamelCase to define all the constants
`Kcounter0 -> kCounterZero
Kcounter1 -> kCounterOne`

2023-08-18 16:57 UTC, FranciscoGaraventa commented on lib/utils/ui_constants.dart
> +abstract class UiConstants {
Remember that the constants name are lowerCamelCase

2023-08-18 16:58 UTC, FranciscoGaraventa commented on lib/utils/ui_text.dart
> +abstract class UiText {
Same that i mentioned earlier, validate constants lowerCamelCase

2023-08-18 16:58 UTC, FranciscoGaraventa commented on lib/widgets/core/my_app_bar.dart
> +import 'package:themovietb/widgets/custom_widgets.dart';
relative import

2023-08-18 16:59 UTC, FranciscoGaraventa commented on lib/widgets/core/show_alert_dialog.dart
> +abstract class MyAlertDialog {
This class could be renamed like CustomAlertDialog or something similar

2023-08-18 17:01 UTC, FranciscoGaraventa commented on lib/widgets/core/title_text.dart
> +//End of File
This comment is not necessary

2023-08-18 17:01 UTC, FranciscoGaraventa commented on lib/widgets/movie_genres/genres_display.dart
> +class GenresSection extends StatelessWidget {
You missed to format here and also remove the commented line at the end of the file

2023-08-18 17:02 UTC, FranciscoGaraventa commented on lib/widgets/movie_information/movie_information.dart
> +}
Move all this widgets to different files

2023-08-18 17:02 UTC, FranciscoGaraventa commented on lib/widgets/movie_information/photo_display.dart
> +//End of File
Move all this widgets to different files

2023-08-18 17:03 UTC, FranciscoGaraventa commented on lib/widgets/movie_overview/overview_display.dart
> +class OverviewColumn extends StatelessWidget {
Do you really need to create a new widget to use the ContainerOverview?

2023-08-22 15:16 UTC, MarcosCGlobant requested changes

2023-08-22 15:16 UTC, MarcosCGlobant commented on lib/widgets/custom_widgets.dart
> +
you can remove this extra line

2023-08-22 15:16 UTC, MarcosCGlobant commented on lib/widgets/custom_widgets.dart
> +
and this one as well

2023-08-22 15:16 UTC, MarcosCGlobant commented on lib/main.dart
> +    //return MovieDetails();
if this comment is not needed, remove it

2023-08-22 15:26 UTC, Kevin-Guillen commented on lib/utils/ui_text.dart
> +  static const String kRating = '7,8';
As a general suggestion for the constants name , you should use more representative names to what the constant refers to. In this case for example a better name for this constant might be movieRatingValue. Always taking into account when choosing the name that another developer has to easily identify what it refers to.

2023-08-22 18:04 UTC, matiasilveiro-gl requested changes
Please add a screenshot to the PR description!

2023-08-22 18:04 UTC, matiasilveiro-gl commented on lib/utils/ui_text.dart
As most of the constants are related to a specific movie (and this app will grow to show the details of different movies) I'd do this:
- Create a `Movie` class (useful for Modules 3 and up).
- Create a mocked movie instance for the Super Mario movie.
- Make all widgets depend on the `Movie` class parameters, instead of the constants

2023-08-22 18:04 UTC, matiasilveiro-gl commented on lib/utils/ui_text.dart
> +  static const String kIncrement = 'increment';
Remove this, as you're using the `enum class` below

2023-08-22 18:04 UTC, matiasilveiro-gl commented on lib/widgets/core/custom_alert_dialog.dart
> +  static void showAlertDialog(BuildContext context) {
I'd rename this as `showUpcomingAlertDialog`, to express what's intended to do in a clearer way.

2023-08-22 18:04 UTC, matiasilveiro-gl commented on lib/widgets/movie_genres/genres_display.dart
> +import 'package:themovietb/widgets/custom_widgets.dart';
Relative import

2023-08-22 18:04 UTC, matiasilveiro-gl commented on lib/widgets/movie_genres/genres_display.dart
> +          ),
You could replace most of this with a `ListView.builder`

2023-08-22 18:04 UTC, matiasilveiro-gl commented on lib/widgets/movie_information/my_title.dart
> +class MyTitle extends StatelessWidget {
I'd choose a more suitable name for this widget. Where is it used? Is this the app title or the movie title?
Also, you could receive the title as a parameter.

2023-08-22 18:04 UTC, matiasilveiro-gl commented on lib/widgets/movie_information/rating.dart
> +        UiText.kRating,
This rating should be a parameter of the widget

2023-08-22 18:04 UTC, matiasilveiro-gl commented on lib/widgets/movie_information/release_date.dart
> +        UiText.kReleaseDate,
Parameter

2023-08-22 18:04 UTC, matiasilveiro-gl commented on lib/widgets/movie_information/small_photo.dart
This could be deleted and moved inside the `SmallPhotocontainer`

2023-08-22 21:54 UTC, FranciscoGaraventa commented on lib/widgets/core/horizontal_spacer.dart
> +class HorizontalSpacer extends StatelessWidget {
Do you really need to wrap this as a new widget?

2023-08-22 21:55 UTC, FranciscoGaraventa commented on lib/widgets/core/like_button_spacer.dart
> +class LikeButtonEndSpacer extends StatelessWidget {
Do you really need to wrap this as a new widget?

2023-08-22 21:56 UTC, FranciscoGaraventa commented on lib/widgets/core/my_custom_app.dart
> +}
Move enum to another file

2023-08-22 21:56 UTC, FranciscoGaraventa commented on lib/widgets/core/my_custom_app.dart
> +            sharedPreferenceInstance.setInt(UiText.kStringCounter, _counter);
trailing comma

2023-08-22 21:57 UTC, FranciscoGaraventa commented on lib/widgets/core/vertical_spacer.dart
> +class VerticalSpacer extends StatelessWidget {
Do you really need to wrap this as a new widget?

2023-08-23 15:12 UTC, LeonardoMolleker approved these changes

2023-08-23 15:38 UTC, matiasilveiro-gl requested changes

2023-08-23 15:38 UTC, matiasilveiro-gl commented on lib/widgets/core/screens/screen_movie_details.dart
> +  ];
The genres list should be a property of the movie, as they're related to this particular movie!

2023-08-24 13:10 UTC, matiasilveiro-gl approved these changes
No new comments!

2023-08-24 13:59 UTC, MarcosCGlobant approved these changes

2023-08-24 14:25 UTC, Kevin-Guillen approved these changes

2023-08-24 19:51 UTC, FranciscoGaraventa approved these changes
LG

2023-08-25 13:52 UTC, merged